name: Create release

on:
  push:
    tags: [ v* ]
  workflow_dispatch: # Manual trigger

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set release tag
        id: release_tag
        run: |
          RELEASE_TAG="${{ github.head_ref }}"
          echo "::set-output name=tag::${RELEASE_TAG}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.release_tag.outputs.tag }}
          release_name: ${{ steps.release_tag.outputs.tag }}
          body: |
            Release information: https://github.com/argoproj/argo-cd/releases/tag/${{ steps.release_tag.outputs.tag }}
          draft: false
          prerelease: false
