name: Create tag

on:
  pull_request:
    types:
      - closed
  workflow_dispatch: # Manual trigger

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set release tag
        id: release_tag
        run: |
          RELEASE_TAG="${{ github.head_ref }}"
          echo "::set-output name=tag::${RELEASE_TAG}"

      - name: Create tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
#            const {DIST_VERSION} = process.env
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.release_tag.outputs.tag }}`,
              sha: context.sha
            })
#          script: |
#            const ref = `refs/tags/${{ steps.release_tag.outputs.tag }}`;
#            const sha = context.sha;
#            const owner = context.repo.owner;
#            const repo = context.repo.repo;
#            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
#            await octokit.git.createRef({ owner, repo, ref, sha });
